name: Basic Code Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install ruff
        run: pip install ruff
      - name: ruff
        run: ruff check .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install poetry
        run: pip install poetry
      - name: Install repo
        run: poetry install --no-interaction --no-ansi
      - name: mypy
        run: mypy .

  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install detect secrets
        run: pip install detect-secrets
      - name: Look for secrets
        run: git ls-files -z | xargs -0 detect-secrets-hook -v

  typos:
    name: "spell check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@master
        with:
          files: .
