name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build BigChem Worker and Start BigChem Services
        run: docker compose up -d --build

      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: "3.9"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install repo
        run: uv sync --all-extras --dev

      - name: Run tests
        run: bash scripts/tests.sh

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov
